//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shuyu.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shuyu.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   クリップボードコピーエラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ClipboardCopyError {
            get {
                return ResourceManager.GetString("ClipboardCopyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クリップボードへのコピーに失敗しました: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ClipboardCopyFailed {
            get {
                return ResourceManager.GetString("ClipboardCopyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   閉じる に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クリップボードにコピー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像をクリップボードにコピーしました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImageCopiedToClipboard {
            get {
                return ResourceManager.GetString("ImageCopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像を保存しました: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImageSaved {
            get {
                return ResourceManager.GetString("ImageSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像保存エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImageSaveError {
            get {
                return ResourceManager.GetString("ImageSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたファイルパスは無効です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidFilePath {
            get {
                return ResourceManager.GetString("InvalidFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存に失敗しました: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像を保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveImage {
            get {
                return ResourceManager.GetString("SaveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ピン留めをすべて削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RemoveAllPinned {
            get {
                return ResourceManager.GetString("RemoveAllPinned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shuyu v{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShuyuVersionFormat {
            get {
                return ResourceManager.GetString("ShuyuVersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shuyu v-.-.- に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShuyuVersionUnknown {
            get {
                return ResourceManager.GetString("ShuyuVersionUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャプチャ開始 (Shift+PrintScreen) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartCapture {
            get {
                return ResourceManager.GetString("StartCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ピン留めの表示/非表示を切り替え に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TogglePinnedVisibility {
            get {
                return ResourceManager.GetString("TogglePinnedVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョン情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VersionInfo {
            get {
                return ResourceManager.GetString("VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定を変更したら「OK」を押してください。低レベルフックは他アプリに影響を与える可能性があるため、必要な場合のみ有効にしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsDescription {
            get {
                return ResourceManager.GetString("SettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsWindowTitle {
            get {
                return ResourceManager.GetString("SettingsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   低レベルキーボードフックを使用する (PrintScreen を抑止する) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UseLowLevelHook {
            get {
                return ResourceManager.GetString("UseLowLevelHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   言語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日本語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LanguageJapanese {
            get {
                return ResourceManager.GetString("LanguageJapanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   システム設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LanguageSystem {
            get {
                return ResourceManager.GetString("LanguageSystem", resourceCulture);
            }
        }
    }
}
